/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package etiproject;

import clases.DBConnect;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ever
 */
public class JDContrato extends javax.swing.JDialog {
    DBConnect con;
    Image imagen = getToolkit().getImage(getClass().getResource("/Imagenes/Iconito.png"));
    String Id;
    ResultSet rs;
    ResultSet rs1;
    private String cliente;
    private String clien;
    
    /**
     * Creates new form JDContrato
     */
    public JDContrato(java.awt.Frame parent, boolean modal, DBConnect con, String Id) {
        super(parent, modal);
        initComponents();
        this.setTitle("Visualización del Contrato");
        jbtGuardar.setVisible(false);
        this.con = con;
        this.Id = Id;
        this.setIconImage(imagen);
        Visualizar(Id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtAtras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbCodigo = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jlbNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlbTipo = new javax.swing.JLabel();
        jtfTipo = new javax.swing.JTextField();
        jlbEstado = new javax.swing.JLabel();
        jtfEstado = new javax.swing.JTextField();
        jlbFecha = new javax.swing.JLabel();
        jlbValidez = new javax.swing.JLabel();
        jtfValidez = new javax.swing.JTextField();
        jlbMonMin = new javax.swing.JLabel();
        jtfMonMin = new javax.swing.JTextField();
        jlbMonMax = new javax.swing.JLabel();
        jtfMonMax = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfAlarma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCliente = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jbtModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 196, 201));

        jbtAtras.setText("Atrás");
        jbtAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtrasActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(195, 196, 201));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jlbCodigo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbCodigo.setText("Código:");

        jtfCodigo.setEnabled(false);
        jtfCodigo.setMinimumSize(new java.awt.Dimension(6, 23));

        jlbNombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbNombre.setText("Nombre:");

        jtfNombre.setEnabled(false);

        jlbTipo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbTipo.setText("Tipo de Contrato:");

        jtfTipo.setEnabled(false);

        jlbEstado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbEstado.setText("Estado:");

        jtfEstado.setEnabled(false);

        jlbFecha.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbFecha.setText("Fecha:");

        jlbValidez.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbValidez.setText("Validez:");

        jtfValidez.setEnabled(false);

        jlbMonMin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbMonMin.setText("Monto Mínimo:");

        jtfMonMin.setEnabled(false);

        jlbMonMax.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbMonMax.setText("Monto Máximo:");

        jtfMonMax.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Alarma en:");

        jtfAlarma.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Cliente:");

        jtfCliente.setEnabled(false);

        jXDatePicker1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jlbValidez)
                            .addGap(77, 77, 77)
                            .addComponent(jtfValidez))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbCodigo)
                                .addComponent(jlbNombre)
                                .addComponent(jlbTipo)
                                .addComponent(jlbEstado)
                                .addComponent(jlbFecha)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(jtfNombre)
                                    .addComponent(jtfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfAlarma)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbMonMax)
                        .addGap(31, 31, 31)
                        .addComponent(jtfMonMax, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbMonMin)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfMonMin, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodigo)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipo)
                    .addComponent(jtfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEstado)
                    .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbFecha)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMonMin)
                    .addComponent(jtfMonMin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMonMax)
                    .addComponent(jtfMonMax, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbValidez)
                    .addComponent(jtfValidez, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jbtModificar.setText("Modificar");
        jbtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("CONTRATO");

        jbtGuardar.setText("Guardar Cambios");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAtras)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAtras)
                    .addComponent(jbtModificar)
                    .addComponent(jbtGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtAtrasActionPerformed

    private void jbtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModificarActionPerformed
       
        jtfCodigo.setVisible(false);
        jtfNombre.setEnabled(true);
        jtfCliente.setEnabled(true);
        jtfTipo.setEnabled(true);
        jtfEstado.setEnabled(true);
        jXDatePicker1.setEnabled(true);
        jtfValidez.setEnabled(true);
        jtfMonMin.setEnabled(true);
        jtfMonMax.setEnabled(true);
        
        jbtModificar.setEnabled(false);
        jbtGuardar.setVisible(true);
        jbtAtras.setText("Cancelar");
        
    }//GEN-LAST:event_jbtModificarActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        try {
            String codigo = jtfCodigo.getText();
            rs=con.Listar("Id_Cliente", "cliente", "where Nombre_Cliente='"+jtfCliente.getText()+"'");
            while (rs.next()){
                 this.cliente=rs.getString("Id_Cliente");
            }
            
            
            Date fecha = jXDatePicker1.getDate();
            if (con.actualizarRegistro("Contrato", "(Id_Contrato='"+jtfCodigo.getText()+"',Id_Cliente='"+cliente+"',Nombre_Contrato='"+jtfNombre.getText()+"',Tipo_Contrato='"+jtfTipo.getText()+"',Estado_Contrato='"
                   +jtfEstado.getText()+"',Fecha_Contrato='"+(fecha.getYear()+1900)+"/"+(fecha.getMonth()+1)+"/"+fecha.getDate()+"',Validez_Contrato='"+jtfValidez.getText()+"',Alarma_Contrato='"+jtfAlarma.getText()+"',Monto_Minimo='"+jtfMonMin.getText()+"',Monto_Maximo='"
                   +jtfMonMax.getText()+"')", "where Id_Contrato="+codigo)){
               JOptionPane.showMessageDialog(rootPane, "Se han guardado los cambios", "Éxito", JOptionPane.INFORMATION_MESSAGE);
           }else{
               JOptionPane.showMessageDialog(rootPane, "No se han podido guardar los cambios", "Error", JOptionPane.ERROR_MESSAGE);
           }
        } catch (SQLException ex) {
            Logger.getLogger(JDContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void Visualizar(String Id) {
        try {
            rs=con.Listar("*", "contrato", "where (Id_Contrato="+Id+")");
            
            while(rs.next()){
                String codigo=rs.getString(1);
                String nombre=rs.getString(3);
                String client=rs.getString(2);
                String tipo=rs.getString(4);
                String estado=rs.getString(5);
                Date fecha=rs.getDate(6);
                String validez=rs.getString(7);
                String monmin=rs.getString(9);
                String monmax=rs.getString(10);
                String alarma=rs.getString(8);
            
                rs1=con.Listar("Nombre_Cliente", "cliente", "where Id_Cliente='"+client+"'");
                while(rs1.next()){
                    this.clien=rs1.getString("Nombre_Cliente");
                }
                
            
            jtfCodigo.setText(codigo);
            jtfNombre.setText(nombre);
            jtfCliente.setText(clien);
            jtfTipo.setText(tipo);
            jtfEstado.setText(estado);
            jXDatePicker1.setDate(fecha);
            jtfValidez.setText(validez);
            jtfMonMin.setText(monmin);
            jtfMonMax.setText(monmax);
            jtfAlarma.setText(alarma);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JDCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDContrato dialog = new JDContrato(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JButton jbtAtras;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JButton jbtModificar;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JLabel jlbEstado;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbMonMax;
    private javax.swing.JLabel jlbMonMin;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbTipo;
    private javax.swing.JLabel jlbValidez;
    private javax.swing.JTextField jtfAlarma;
    private javax.swing.JTextField jtfCliente;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfMonMax;
    private javax.swing.JTextField jtfMonMin;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTipo;
    private javax.swing.JTextField jtfValidez;
    // End of variables declaration//GEN-END:variables
}
