/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package etiproject;

import clases.DBConnect;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Melissa
 */
public class JDMDO extends javax.swing.JDialog {
    DBConnect con;
    Image imagen = getToolkit().getImage(getClass().getResource("/Imagenes/Iconito.png"));
    ResultSet rs;
    ResultSet rs1;
    private final String Id;
    private String categoria;
    /**
     * Creates new form JDMDO
     */
    public JDMDO(java.awt.Frame parent, boolean modal, DBConnect con, String Id) {
        super(parent, modal);
        initComponents();
        this.setTitle("Visualización de Mano de Obra");
        this.setIconImage(imagen);
        this.con=con;
        this.Id=Id;
        jbtGuardar.setVisible(false);
        Visualizar(Id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbCodigo = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jlbItem = new javax.swing.JLabel();
        jtfItem = new javax.swing.JTextField();
        jlbCategoria = new javax.swing.JLabel();
        jtfCategoria = new javax.swing.JTextField();
        jlbDetalles = new javax.swing.JLabel();
        jtfDetalles = new javax.swing.JTextField();
        jlbMinutos = new javax.swing.JLabel();
        jtfMinutos = new javax.swing.JTextField();
        jlbPrecio = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jbtAtras = new javax.swing.JButton();
        jbtModificar = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 196, 201));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("MANO DE OBRA");

        jPanel2.setBackground(new java.awt.Color(195, 197, 201));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jlbCodigo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbCodigo.setText("Código:");

        jtfCodigo.setEditable(false);
        jtfCodigo.setEnabled(false);

        jlbItem.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbItem.setText("ITEM:");

        jtfItem.setEditable(false);
        jtfItem.setEnabled(false);

        jlbCategoria.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbCategoria.setText("Categoría:");

        jtfCategoria.setEditable(false);
        jtfCategoria.setEnabled(false);

        jlbDetalles.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbDetalles.setText("Detalles:");

        jtfDetalles.setEditable(false);
        jtfDetalles.setEnabled(false);

        jlbMinutos.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbMinutos.setText("Cantidad de Minutos:");

        jtfMinutos.setEditable(false);
        jtfMinutos.setEnabled(false);

        jlbPrecio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbPrecio.setText("Precio:");

        jtfPrecio.setEditable(false);
        jtfPrecio.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbMinutos)
                    .addComponent(jlbDetalles)
                    .addComponent(jlbCategoria)
                    .addComponent(jlbItem)
                    .addComponent(jlbCodigo)
                    .addComponent(jlbPrecio))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jtfItem)
                    .addComponent(jtfCategoria)
                    .addComponent(jtfDetalles)
                    .addComponent(jtfMinutos)
                    .addComponent(jtfPrecio))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodigo)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbItem)
                    .addComponent(jtfItem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCategoria)
                    .addComponent(jtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDetalles)
                    .addComponent(jtfDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMinutos)
                    .addComponent(jtfMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrecio)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jbtAtras.setText("Atrás");
        jbtAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtrasActionPerformed(evt);
            }
        });

        jbtModificar.setText("Modificar");
        jbtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModificarActionPerformed(evt);
            }
        });

        jbtGuardar.setText("Guardar Cambios");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAtras))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAtras)
                    .addComponent(jbtModificar)
                    .addComponent(jbtGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModificarActionPerformed
        jtfItem.setEnabled(true);
        jtfCategoria.setEnabled(true);
        jtfDetalles.setEnabled(true);
        jtfMinutos.setEnabled(true);
        jtfPrecio.setEnabled(true);
        
        jbtModificar.setEnabled(false);
        jbtGuardar.setVisible(true);
        jbtAtras.setText("Cancelar");
        
    }//GEN-LAST:event_jbtModificarActionPerformed

    private void jbtAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtAtrasActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        
        String codigo=jtfCodigo.getText();
        if (con.actualizarRegistro("mano_de_obra", "Id_MdO='"+jtfCodigo.getText()+"',Servicio_MdO='"+jtfItem.getText()+"',Id_Categoria='"+jtfCategoria.getText()+"',Detalles_MdO='"
                +jtfDetalles.getText()+"',Minutos_MdO='"+jtfMinutos.getText()+"',Precio_MdO='"+jtfPrecio.getText()+"'", "where Id_MdO='"+codigo+"'")){
            JOptionPane.showMessageDialog(rootPane, "Se han guardado los cambios", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se han podido guardar los cambios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void Visualizar(String Id) {
        try {
            rs=con.Listar("*", "mano_de_obra", "where (Id_MdO="+Id+")");
            
            while(rs.next()){
                String codigo=rs.getString(1);
                String item=rs.getString(4);
                String categ=rs.getString(2);
                String detalles=rs.getString(5);
                String minutos=rs.getString(6);
                String precio=rs.getString(3);
            
                rs1=con.Listar("Nombre_Categoria", "Categoria_MDO", "where Id_Categoria='"+categ+"'");
                while(rs1.next()){
                    this.categoria=rs1.getString("Nombre_Categoria");
                }
                
            jtfCodigo.setText(codigo);
            jtfItem.setText(item);
            jtfCategoria.setText(categoria);
            jtfDetalles.setText(detalles);
            jtfMinutos.setText(minutos);
            jtfPrecio.setText(precio);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JDCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDMDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDMDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDMDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDMDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDMDO dialog = new JDMDO(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtAtras;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JButton jbtModificar;
    private javax.swing.JLabel jlbCategoria;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JLabel jlbDetalles;
    private javax.swing.JLabel jlbItem;
    private javax.swing.JLabel jlbMinutos;
    private javax.swing.JLabel jlbPrecio;
    private javax.swing.JTextField jtfCategoria;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDetalles;
    private javax.swing.JTextField jtfItem;
    private javax.swing.JTextField jtfMinutos;
    private javax.swing.JTextField jtfPrecio;
    // End of variables declaration//GEN-END:variables
}
