/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package etiproject;

import clases.DBConnect;
import clases.Usuario;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXComboBox;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Ever
 */
public class jDNAsistencia extends javax.swing.JDialog {
    DBConnect con;
    Usuario user;
    Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/Iconito.png"));
    DefaultTableModel m;
    /**
     * Creates new form jDNAsistencia
     */
    public jDNAsistencia(java.awt.Frame parent, boolean modal, DBConnect con,Usuario user) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registrar Asistencia");
        this.setIconImage(imagen);
        this.con = con;
        this.user = user;
        Date hoy = new Date();
        jXDatePicker1.setDate(hoy);
        actualizarCombo("Id_usuario", "usuario", "", jXCAliasUsu);
        actualizarCombo("Id_Orden", "ODS", "where Estado_Orden= 'Activo'", jXCBODS);
        actualizarCombo("Nombre_Sucursal", "sucursal", "", jXCBSucursal);
        
        m = (DefaultTableModel) jTODs.getModel();
        jTODs.setModel(m);
        
    }
    
    
    public void actualizarCombo(String campo,String tabla,String condicion, JXComboBox combo){
        try {
            
            combo.removeAllItems();
            ResultSet r=null;
            r= con.Listar(campo, tabla, condicion);
            while(r.next()){
                combo.addItem(r.getString(campo));
            }
            AutoCompleteDecorator.decorate(combo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jPAsistencia = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSHEntrada = new javax.swing.JSpinner();
        jSMEntrada = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSHSalida = new javax.swing.JSpinner();
        jSMSalida = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSAlmuerzo = new javax.swing.JSpinner();
        jSMExtra = new javax.swing.JSpinner();
        jSHExtra = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXCAliasUsu = new org.jdesktop.swingx.JXComboBox();
        jXLArea = new javax.swing.JLabel();
        jXTArea = new org.jdesktop.swingx.JXTextField();
        jPODSAsist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTODs = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSMInicio = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSHInicio = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSHUtil = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSMUtil = new javax.swing.JSpinner();
        jBAgregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jXCBODS = new org.jdesktop.swingx.JXComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jXCBSucursal = new org.jdesktop.swingx.JXComboBox();
        jBAddODS = new javax.swing.JButton();
        jBAddSucursal = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPFondo.setBackground(new java.awt.Color(195, 196, 201));

        jLabel1.setText("Asistencia de la fecha:");

        jPAsistencia.setBackground(new java.awt.Color(195, 196, 201));
        jPAsistencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel2.setText("Nombre Usuario:");

        jLabel3.setText("Hora de Entrada:");

        jLabel4.setText(":");

        jSHEntrada.setModel(new javax.swing.SpinnerNumberModel(6, 0, 24, 1));

        jSMEntrada.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel5.setText(":");

        jLabel6.setText("Hora de Salida:");

        jSHSalida.setModel(new javax.swing.SpinnerNumberModel(6, 0, 24, 1));

        jSMSalida.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel7.setText("Hs.");

        jLabel8.setText("Hs.");

        jLabel9.setText("Almuerzo:");

        jSAlmuerzo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        jSMExtra.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jSHExtra.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        jLabel11.setText(":");

        jLabel12.setText("Extra:");

        jScrollPane2.setViewportView(jXCAliasUsu);

        jXLArea.setText("Área:");

        javax.swing.GroupLayout jPAsistenciaLayout = new javax.swing.GroupLayout(jPAsistencia);
        jPAsistencia.setLayout(jPAsistenciaLayout);
        jPAsistenciaLayout.setHorizontalGroup(
            jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAsistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAsistenciaLayout.createSequentialGroup()
                        .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAsistenciaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(jPAsistenciaLayout.createSequentialGroup()
                                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPAsistenciaLayout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jXTArea, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPAsistenciaLayout.createSequentialGroup()
                                        .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPAsistenciaLayout.createSequentialGroup()
                                                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPAsistenciaLayout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jSHEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(3, 3, 3)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSMEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAsistenciaLayout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jSAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jSHSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jSHExtra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPAsistenciaLayout.createSequentialGroup()
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jSMSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)))
                                            .addGroup(jPAsistenciaLayout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(jSMExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(66, 66, 66)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPAsistenciaLayout.createSequentialGroup()
                        .addComponent(jXLArea)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPAsistenciaLayout.setVerticalGroup(
            jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAsistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jSHEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSMEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jSHSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSMSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jSAlmuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSHExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSMExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLArea)
                    .addComponent(jXTArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPODSAsist.setBackground(new java.awt.Color(195, 196, 201));
        jPODSAsist.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jTODs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ODS", "Hora de Inicio", "Horas Ocupadas", "Hora Nominal", "Sucursal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTODs);

        jLabel10.setText("Orden De Servicio:");

        jLabel13.setText("Hora de Inicio:");

        jSMInicio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel14.setText("Hs.");

        jLabel15.setText(":");

        jSHInicio.setModel(new javax.swing.SpinnerNumberModel(6, 0, 24, 1));

        jLabel16.setText("Sucursal:");

        jLabel17.setText("Hs.");

        jSHUtil.setModel(new javax.swing.SpinnerNumberModel(2, 0, 24, 1));
        jSHUtil.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSHUtilStateChanged(evt);
            }
        });

        jLabel18.setText(":");

        jLabel19.setText("Hora Útil:");

        jSMUtil.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jBAgregar.setText("Agregar ODS");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jXCBODS);

        jScrollPane4.setViewportView(jXCBSucursal);

        jBAddODS.setText("+");
        jBAddODS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddODSActionPerformed(evt);
            }
        });

        jBAddSucursal.setText("+");
        jBAddSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPODSAsistLayout = new javax.swing.GroupLayout(jPODSAsist);
        jPODSAsist.setLayout(jPODSAsistLayout);
        jPODSAsistLayout.setHorizontalGroup(
            jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPODSAsistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPODSAsistLayout.createSequentialGroup()
                        .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel10))
                        .addGap(9, 9, 9)
                        .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAddSucursal)
                            .addComponent(jBAddODS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPODSAsistLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel13))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPODSAsistLayout.createSequentialGroup()
                                .addComponent(jSHUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSMUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPODSAsistLayout.createSequentialGroup()
                                .addComponent(jSHInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSMInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAgregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPODSAsistLayout.setVerticalGroup(
            jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPODSAsistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jSHInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSMInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jBAddODS))
                    .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jSHUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSMUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jBAddSucursal))
                    .addGroup(jPODSAsistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jBAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFondoLayout.createSequentialGroup()
                        .addComponent(jPAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPODSAsist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPFondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPFondoLayout.createSequentialGroup()
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPODSAsist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSHUtilStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSHUtilStateChanged

    }//GEN-LAST:event_jSHUtilStateChanged

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        String Ods;
        Ods = (String) jXCBODS.getSelectedItem();

        boolean OdsVacio = false;
        if(Ods==""){
            OdsVacio=true;
        }else{
            OdsVacio=false;
        }

        boolean OdsRepetido= false;
        for(int i=0;i<jTODs.getRowCount();i++){
            if(Ods.equals(( String)jTODs.getValueAt(i, 0))){
                JOptionPane.showMessageDialog(rootPane, "Ya ha agregado esta ODS", "Error", JOptionPane.ERROR_MESSAGE);
                OdsRepetido = true;
            }
        }
        if(!OdsRepetido && !OdsVacio){
            String vec[] = new String[5];
            Integer nominal;
            if(((int) jSHInicio.getValue())%2==0){
                nominal=((int) jSHInicio.getValue());
            }else{
                nominal = ((int) jSHInicio.getValue()) -1;
            }
            vec[0]=Ods;
            vec[4]=String.valueOf(jXCBSucursal.getSelectedIndex());
            vec[3]=nominal.toString();
            vec[2]=(String) String.valueOf(jSHInicio.getValue())+":"+String.valueOf(jSMInicio.getValue());
            vec[1]= (String) String.valueOf(jSHUtil.getValue())+":"+String.valueOf(jSMUtil.getValue());

            m.addRow(vec);

        }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBAddODSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddODSActionPerformed
        new JDNODS(null, true, con,user).setVisible(true);
        actualizarCombo("Id_orden", "ODS", "", jXCBODS);
    }//GEN-LAST:event_jBAddODSActionPerformed

    private void jBAddSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddSucursalActionPerformed
        new jDNSucursal(null, true, con).setVisible(true);
        actualizarCombo("Nombre_Sucursal", "Sucursal", "", jXCBSucursal);
    }//GEN-LAST:event_jBAddSucursalActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        Time llegada = new Time((int)jSHEntrada.getValue(), (int) jSMEntrada.getValue(),0);
        Time salida = new Time((int)jSHSalida.getValue(),(int)jSMSalida.getValue(),0);
        Time extra = new Time((int) jSHExtra.getValue(),(int)jSMExtra.getValue(),0);
        boolean succes=true;
        if(con.Altas("Asistencia", "", "('"+(jXDatePicker1.getDate().getYear()+1999)+"/"+(jXDatePicker1.getDate().getMonth()+1)+"/"+(jXDatePicker1.getDate().getDate())+"','"+String.valueOf(jXCAliasUsu.getSelectedItem())+"','"
            +llegada.toString().substring(0, llegada.toString().length()-3)+"','"+salida.toString().substring(0, salida.toString().length()-3)+"',"+jSAlmuerzo.getValue()+","+extra.toString().substring(0, extra.toString().length()-3)+",'"+jXTArea.getText()+"'")){
        for(int i=0;i<jTODs.getRowCount();i++){
            if(!con.Altas("detalle_asistencia", "", "('"+(jXDatePicker1.getDate().getYear()+1999)+"/"+(jXDatePicker1.getDate().getMonth()+1)+"/"+(jXDatePicker1.getDate().getDate())+"','"+String.valueOf(jXCAliasUsu.getSelectedItem())+"',"+String.valueOf(jTODs.getValueAt(i, 4))+",'"+jTODs.getValueAt(i, 0)+"','"+jTODs.getValueAt(i, 1)+"',"+jTODs.getValueAt(i, 3)+",'"+jTODs.getValueAt(i, 2)+"')")){
                succes = false;
            }
        }
        }else{
            succes=false;
        }
        if(succes){
            JOptionPane.showMessageDialog(rootPane, "La asistencia se ha registrado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            if(JOptionPane.showConfirmDialog(rootPane, "¿Desea registrar otra asistencia?","Consulta", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                m =new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "ODS", "Hora de Inicio", "Horas Ocupadas", "Hora Nominal", "Sucursal", "Área"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, true
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                };
                jTODs.setModel(m);
            }else{
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al momento de registrar la asistencia.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDNAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDNAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDNAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDNAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDNAsistencia dialog = new jDNAsistencia(new javax.swing.JFrame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddODS;
    private javax.swing.JButton jBAddSucursal;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAsistencia;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPODSAsist;
    private javax.swing.JSpinner jSAlmuerzo;
    private javax.swing.JSpinner jSHEntrada;
    private javax.swing.JSpinner jSHExtra;
    private javax.swing.JSpinner jSHInicio;
    private javax.swing.JSpinner jSHSalida;
    private javax.swing.JSpinner jSHUtil;
    private javax.swing.JSpinner jSMEntrada;
    private javax.swing.JSpinner jSMExtra;
    private javax.swing.JSpinner jSMInicio;
    private javax.swing.JSpinner jSMSalida;
    private javax.swing.JSpinner jSMUtil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTODs;
    private org.jdesktop.swingx.JXComboBox jXCAliasUsu;
    private org.jdesktop.swingx.JXComboBox jXCBODS;
    private org.jdesktop.swingx.JXComboBox jXCBSucursal;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel jXLArea;
    private org.jdesktop.swingx.JXTextField jXTArea;
    // End of variables declaration//GEN-END:variables
}
