/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package etiproject;

import clases.DBConnect;
import clases.Usuario;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ever
 */
public class JDNPDM extends javax.swing.JDialog {
    DBConnect con;
    Image imagen = getToolkit().getImage(getClass().getResource("/Imagenes/Iconito.png"));
    private String id="";
    ResultSet rs;
    DefaultTableModel m;
    Usuario user;
    private String fecha;
    /**
     * Creates new form JDNPDM
     */
    public JDNPDM(java.awt.Frame parent, boolean modal, DBConnect con, Usuario user) {
        super(parent, modal);
        initComponents();
        this.setTitle("Nuevo Pedido de Material");
        this.con=con;
        this.user=user;
        this.setIconImage(imagen);
        if(jChBContrato.isSelected()){
            this.jtfContrato.setEnabled(true);
        }
        Calendar c = new GregorianCalendar(); 
            String dia, mes, anho;
            dia = Integer.toString(c.get(Calendar.DATE));
            mes = Integer.toString(c.get(Calendar.MONTH));
            anho = Integer.toString(c.get(Calendar.YEAR));
	   
	   fecha= anho + "-" + mes +"-" + dia;
        this.jtfFecha.setText(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfContrato = new javax.swing.JTextField();
        jtfRubro = new javax.swing.JTextField();
        jtfFecha = new javax.swing.JTextField();
        jtfObs = new javax.swing.JTextField();
        jtfRelaAnt = new javax.swing.JTextField();
        jtfRelSig = new javax.swing.JTextField();
        jChBContrato = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMateriales = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jbtSeleccionar = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JTextField();
        jbtCancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("Eliminar");
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 196, 201));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("PEDIDO DE MATERIAL");

        jPanel2.setBackground(new java.awt.Color(195, 196, 201));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel3.setText("Contrato:");

        jLabel4.setText("Rubro:");

        jLabel5.setText("Fecha:");

        jLabel6.setText("Observación:");

        jLabel7.setText("Relacionado Anterior:");

        jLabel8.setText("Relacionado Siguiente:");

        jtfContrato.setEnabled(false);
        jtfContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfContratoActionPerformed(evt);
            }
        });

        jtfRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRubroActionPerformed(evt);
            }
        });

        jtfFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFechaActionPerformed(evt);
            }
        });

        jtfObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfObsActionPerformed(evt);
            }
        });

        jtfRelaAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRelaAntActionPerformed(evt);
            }
        });

        jtfRelSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRelSigActionPerformed(evt);
            }
        });

        jChBContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChBContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfRelSig, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRelaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfObs, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfContrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jChBContrato)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtfContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jChBContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfObs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfRelaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRelSig, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(195, 196, 201));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Materiales");

        jTableMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Herramienta", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMateriales);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setText("Agregar los materiales correspondiente al pedido. ");

        jbtSeleccionar.setText("Seleccionar");
        jbtSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtSeleccionar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtSeleccionar)
                .addContainerGap())
        );

        jbtCancelar.setText("Cancelar");

        jButton2.setText("Agregar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancelar)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jtfRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRubroActionPerformed
        jtfRubro.transferFocus();
    }//GEN-LAST:event_jtfRubroActionPerformed

    private void jtfFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFechaActionPerformed
        jtfFecha.transferFocus();
    }//GEN-LAST:event_jtfFechaActionPerformed

    private void jtfObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfObsActionPerformed
        jtfObs.transferFocus();
    }//GEN-LAST:event_jtfObsActionPerformed

    private void jtfRelaAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRelaAntActionPerformed
        jtfRelaAnt.transferFocus();
    }//GEN-LAST:event_jtfRelaAntActionPerformed

    private void jtfRelSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRelSigActionPerformed
        jtfRelSig.transferFocus();
    }//GEN-LAST:event_jtfRelSigActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            if(jChBContrato.isSelected()){
                    String contrato=jtfContrato.getText();
                    rs=con.Listar("Id_Contrato", "contrato", "where Nombre_Contrato='"+contrato+"'");
                    while(rs.next()){
                        this.id = rs.getString("Id_Contrato");
                    }
                    
                    if(con.Altas("pedido", "", "('"+jtfCodigo.getText()+"','"+id+"','"+jtfRubro.getText()+"','"+user.getAlias()+"','"
                        +jtfFecha.getText()+"','Esperando aprobación','"+jtfObs.getText()+"','"+jtfRelaAnt.getText()+"','"+jtfRelSig.getText()+"')")){
                    
                        for(int i=0; i<jTableMateriales.getRowCount(); i++) {
                            String idStock=jTableMateriales.getValueAt(i, 0).toString();
                            String cantidad=jTableMateriales.getValueAt(i, 2).toString();

                            con.Altas("detalle_pedido", "", "('"+jtfCodigo.getText()+"','"+idStock+"','"+cantidad+"')");

                        }
                        
                        JOptionPane.showMessageDialog(rootPane, "Se ha registrado el pedido de materiales", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "No se ha podido registrar el pedido de materiales", "Error", JOptionPane.ERROR_MESSAGE);

                    }
                    
                    if(con.Altas("odc", "", "('"+jtfCodigo.getText()+"','"+jtfFecha.getText()+"','"+id+"','En espera','"+jtfRubro.getText()+"','"
                        +jtfRubro.getText()+"','"+jtfObs.getText()+"','plazo','"+jtfCodigo.getText()+"','"+jtfRelSig.getText()+"')")){
                        JOptionPane.showMessageDialog(rootPane, "Se ha creado la Orden de Compra. Para aprobarla ingrese a la lista ODC del menú principal.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "No se ha podido crear la orden de compra", "Error", JOptionPane.ERROR_MESSAGE);

                    }
                    
                    
                    
                    
            }else{
                this.id=null;
                
                if(con.Altas("pedido", "", "('"+jtfCodigo.getText()+"',"+id+",'"+jtfRubro.getText()+"','"+user.getAlias()+"','"
                        +jtfFecha.getText()+"','Esperando aprobación','"+jtfObs.getText()+"','"+jtfRelaAnt.getText()+"','"+jtfRelSig.getText()+"')")){
                    
                    for(int i=0; i<jTableMateriales.getRowCount(); i++) {
                        String idStock=jTableMateriales.getValueAt(i, 0).toString();
                        String cantidad=jTableMateriales.getValueAt(i, 2).toString();

                        con.Altas("detalle_pedido", "", "('"+jtfCodigo.getText()+"','"+idStock+"','"+cantidad+"')");

                    }
                    
                    JOptionPane.showMessageDialog(rootPane, "Se ha registrado el pedido de materiales", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se ha podido registrar el pedido de materiales", "Error", JOptionPane.ERROR_MESSAGE);

                }
                
                if(con.Altas("odc", "", "('"+jtfCodigo.getText()+"','"+jtfFecha.getText()+"',"+id+",'En espera','"+jtfRubro.getText()+"','"
                        +jtfRubro.getText()+"','"+jtfObs.getText()+"','plazo','"+jtfRelaAnt.getText()+"','"+jtfRelSig.getText()+"')")){
                JOptionPane.showMessageDialog(rootPane, "Se ha creado la Orden de Compra. Para aprobarla ingrese a la lista ODC del menú principal.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se ha podido crear la orden de compra", "Error", JOptionPane.ERROR_MESSAGE);

                }
                
                
                
                
            }
            
            
            
            
            
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(JDNPDM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jChBContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChBContratoActionPerformed
        if(jChBContrato.isSelected()){
            this.jtfContrato.setEnabled(true);
        }else{
            this.jtfContrato.setEnabled(false);
        }
    }//GEN-LAST:event_jChBContratoActionPerformed

    private void jbtSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSeleccionarActionPerformed
        JDAgregarMaterial agregar=new JDAgregarMaterial(null, true, con);
        agregar.setVisible(true);
        m=(DefaultTableModel) jTableMateriales.getModel();
        jTableMateriales.setModel(m);
        boolean bandera=false;
        int indice=0;
        for(int h=0;h<agregar.f;h++){
          bandera = false;
          Integer cantidad=0;
          String codigo="";
          String codigo2="";
          indice = 0;
            
            
            String vec[]= new String[3];
            
            int hasta= jTableMateriales.getRowCount();
            
            System.out.println(String.valueOf(hasta));
            
                for (int j=0;j<hasta;j++){
                    bandera=false;
                    codigo = String.valueOf(jTableMateriales.getValueAt(j, 0));
                    codigo2 = String.valueOf(agregar.Lista[h][0]);
                    if(codigo.equals(codigo2)){
                        bandera=true;
                        indice = j;
                        System.out.println("Hooolaa");
                        break;
                    }
                    System.out.println(jTableMateriales.getValueAt(j, 0));
                    
                }
            
            
            if(bandera==false){
                try {
                    
                        vec[0]= agregar.Lista[h][0];
                        vec[1]= agregar.Lista[h][1];
                        vec[2]= agregar.Lista[h][2];
                        m.addRow(vec);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }else{
                     try {
                            rs.next();

                            String canactual=String.valueOf(jTableMateriales.getValueAt(indice, 2));
                            cantidad=Integer.valueOf(agregar.Lista[h][2])+Integer.valueOf(canactual);
                            jTableMateriales.setValueAt(cantidad, indice, 2);

                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Error2");
                        }
            }
        }
           System.out.println(bandera+" "+indice);
        
        
    }//GEN-LAST:event_jbtSeleccionarActionPerformed

    private void jtfContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContratoActionPerformed
        jtfContrato.transferFocus();
    }//GEN-LAST:event_jtfContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDNPDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDNPDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDNPDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDNPDM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDNPDM dialog = new JDNPDM(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jChBContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMateriales;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtSeleccionar;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfContrato;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfObs;
    private javax.swing.JTextField jtfRelSig;
    private javax.swing.JTextField jtfRelaAnt;
    private javax.swing.JTextField jtfRubro;
    // End of variables declaration//GEN-END:variables
}
