/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDNUsuario.java
 *
 * Created on 08/09/2012, 11:44:04 AM
 */
package etiproject;

import clases.DBConnect;
import clases.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileView;

/**
 *
 * @author Edgar
 */
public class JDNUsuario extends javax.swing.JDialog {
    
   
    DBConnect con;
    Usuario user;
    double zoom = 1.0; 
    boolean alias_valid=false;
    boolean contra_valid=false;
    boolean correo_valid=false;
    Image imagen = getToolkit().getImage(getClass().getResource("/Imagenes/Iconito.png"));
    /** Creates new form JDNUsuario */
    
     public JDNUsuario(java.awt.Frame parent, boolean modal,DBConnect con,Usuario user) {
        super(parent, modal);
        initComponents();
        this.setIconImage(imagen);
        setLocationRelativeTo(null);
        setTitle("Nuevo Usuario");
        
        jLNuevo.setText("Nuevo Usuario");
        this.con = con;
        this.user = user;
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLNuevo = new javax.swing.JLabel();
        jPBotones = new javax.swing.JPanel();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jlapellido = new javax.swing.JLabel();
        jtapellido = new javax.swing.JTextField();
        jLContraseña = new javax.swing.JLabel();
        jPContraseña = new javax.swing.JPasswordField();
        jLContraseña2 = new javax.swing.JLabel();
        jPContraseña2 = new javax.swing.JPasswordField();
        jlAlias = new javax.swing.JLabel();
        jtAlias = new javax.swing.JTextField();
        jlTelefono = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jlDireccion = new javax.swing.JLabel();
        jTDireccion = new javax.swing.JTextField();
        jLIcon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();
        JTRuta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(195, 196, 201));

        jLNuevo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLNuevo.setText("Nuevo Usuario");

        jPBotones.setBackground(new java.awt.Color(195, 196, 201));
        jPBotones.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });
        jPBotones.add(jBAceptar);

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPBotones.add(jBCancelar);

        jPanel1.setBackground(new java.awt.Color(195, 196, 201));

        jLNombre.setText("Nombre:");

        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });

        jlapellido.setText("Apellido:");

        jLContraseña.setText("Contraseña:");

        jLContraseña2.setBackground(new java.awt.Color(255, 51, 51));
        jLContraseña2.setText("Conf. Contraseña");

        jPContraseña2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPContraseña2CaretUpdate(evt);
            }
        });
        jPContraseña2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPContraseña2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPContraseña2FocusLost(evt);
            }
        });

        jlAlias.setText("Alias:");

        jtAlias.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtAliasCaretUpdate(evt);
            }
        });
        jtAlias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtAliasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAliasFocusLost(evt);
            }
        });

        jlTelefono.setText("Teléfono:");

        jlDireccion.setText("Correo Electrónico:");

        jTDireccion.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTDireccionCaretUpdate(evt);
            }
        });
        jTDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTDireccionFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jlTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlAlias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLContraseña2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlapellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jTNombre)
                    .addComponent(jPContraseña)
                    .addComponent(jPContraseña2)
                    .addComponent(jtAlias)
                    .addComponent(jtTelefono)
                    .addComponent(jTDireccion)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vendedor_32x32.png"))); // NOI18N

        jButton1.setText("Examinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jXImageView1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jXImageView1MouseWheelMoved(evt);
            }
        });

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        JTRuta.setEnabled(false);

        jLabel2.setText("Imagen de Usuario:");

        jLabel3.setText("Imagen de Usuario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLNuevo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(JTRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXImageView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLNuevo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        
        
            if(!jtAlias.getText().equals("")){
                if(!jTNombre.getText().equals("")){
                   if(JTRuta.getText().equals("")){
                       /* la carga en base de datos se hace en el siguiente orden para la tabla usuario
                        * Id_usuario, Id_nivel, password_systema, tel_usuario, correo_usuario, Contraseña_correo, imagen_usuario,zoom_imagen_usuario
                        * En caso de que se haya seleccionado una imagen se procede a dar alta a todos los campos que no sean la imagen y luego se actualiza con la llamada
                        * a una función de la clase DBConnect que está preparada para recibir una imagen.
                        */
                        
                       // SHA1() es una función de MySQL que se encarga de encryptar el dato que recibe, 
                       // Es una buena práctica dejar que sólo el usuario conozca su contraseña.
                       
                       
                       
                       
                       if(alias_valid && contra_valid && correo_valid ){
                           if(con.Altas("usuario", "", "('"+jtAlias.getText()+"','"+jTNombre.getText()+" "+jtapellido.getText()+"',0,SHA1('"+jPContraseña.getText()+"'),'"+jtTelefono.getText()+"','"+jTDireccion.getText()+"','',0);")){
                               JOptionPane.showMessageDialog(rootPane, "Usuario Creado con Éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                               
                               /*
                                * El único caso en el que el usuario que se recibe como argumento
                                * es el Admin, es cuando se esta creando el primer usuario del sistema,
                                * por lo que en caso de que ese sea el caso, al usuario a crear
                                * se le dan privilegios de administrador, en caso contrario
                                * se abre la ventana de privilegios, para la asignacion de manual de
                                * sus privilegios.
                                */
                               
                               if(!user.getAlias().equals("Admin")){
                                   new JDNPermisos(null, true, con,user.getAlias(),jtAlias.getText()).setVisible(true);
                               }else{
                                   CrearPermisos();
                               }
                           }else{
                               JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al momento de guardar los datos del Usuario", "Error", JOptionPane.ERROR_MESSAGE);
                           }
                       }else{
                           JOptionPane.showMessageDialog(rootPane, "EL alias o su correo no son correctos, o sus contraseñas no coinciden.", "Error", JOptionPane.ERROR);
                       }
                       
                   }else{
                       if(alias_valid && contra_valid && correo_valid ){
                           if(con.Altas("usuario", "", "('"+jtAlias.getText()+"','"+jTNombre.getText()+" "+jtapellido.getText()+"',0,SHA1('"+jPContraseña.getText()+"'),'"+jtTelefono.getText()+"','"+jTDireccion.getText()+"','',"+zoom+");")){

                               FileInputStream foto=null;
                               try {
                                    foto = new FileInputStream(JTRuta.getText());
               
                              } catch (FileNotFoundException ex) {
                                    JOptionPane.showMessageDialog(rootPane,ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                                 }
                       
                                if(!user.getAlias().equals("Admin")){
                                   new JDNPermisos(null, true, con,user.getAlias(),jtAlias.getText()).setVisible(true);
                               }else{
                                    CrearPermisos();
                                }
                                
                              con.actualizarRegistro(jtAlias.getText(),foto);
                               JOptionPane.showMessageDialog(rootPane, "Usuario Creado con Éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                               
                               
                              
                               
                            }else{
                                      JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al momento de guardar los datos del Usuario", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                       
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "El campo Nombre no debe estar vacío","Atención",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "El campo Alias no debe estar vacío","Atencion",JOptionPane.ERROR_MESSAGE);
            }
            if(JOptionPane.showConfirmDialog(rootPane, "¿Desea Crear Otro Usuario?", "Atención", JOptionPane.YES_NO_OPTION)==JOptionPane.NO_OPTION){
                this.dispose();
            }
        
            
        
}//GEN-LAST:event_jBAceptarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File archive = obtenerArchivo();
        
        if (archive.exists() && archive != null)
         JTRuta.setText(archive.getPath());
        
        if(JTRuta.getText()!=""){
            Image imagen = getToolkit().getImage(JTRuta.getText());
                System.out.println();
                File file = new File(JTRuta.getText());
                try {
                    jXImageView1.setImage(file);

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jXImageView1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jXImageView1MouseWheelMoved
         if(evt.getPreciseWheelRotation()>0){
            zoom-=0.1;
            jXImageView1.setScale(zoom);
        }else{
            zoom+=0.1;
            jXImageView1.setScale(zoom);
        }
    }//GEN-LAST:event_jXImageView1MouseWheelMoved

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jtAliasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtAliasCaretUpdate
        ResultSet res = null;
        

        try {
            res = con.Listar("COUNT(Id_usuario)", "usuario", "where Id_usuario='"+jtAlias.getText()+"'");
            res.next();
            if(res.getInt(1)==0){
               jtAlias.setBackground(new java.awt.Color(102, 255, 102));
               alias_valid = true;
            }else{
                jtAlias.setBackground(new java.awt.Color(255, 51, 51));
                alias_valid = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(JDNUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                   
        
    }//GEN-LAST:event_jtAliasCaretUpdate

    private void jPContraseña2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPContraseña2CaretUpdate
        if(jPContraseña.getText().equals(jPContraseña2.getText())){
            jPContraseña2.setBackground(new java.awt.Color(102, 255, 102));
            contra_valid = true;
        }else{
            jPContraseña2.setBackground(new java.awt.Color(255, 51, 51));
            contra_valid = false;
        }
    }//GEN-LAST:event_jPContraseña2CaretUpdate

    private void jPContraseña2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPContraseña2FocusLost
        jPContraseña2.setBackground(Color.white);
    }//GEN-LAST:event_jPContraseña2FocusLost

    private void jPContraseña2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPContraseña2FocusGained
        jPContraseña2CaretUpdate(null);
    }//GEN-LAST:event_jPContraseña2FocusGained

    private void jTDireccionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTDireccionCaretUpdate
        if(jTDireccion.getText().indexOf('@')!=-1){
            jTDireccion.setBackground(new java.awt.Color(102, 255, 102));
            correo_valid = true;
        }else{
            jTDireccion.setBackground(new java.awt.Color(255, 51, 51));
            correo_valid = false;
        }
    }//GEN-LAST:event_jTDireccionCaretUpdate

    private void jtAliasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAliasFocusLost
        jtAlias.setBackground(Color.white);
    }//GEN-LAST:event_jtAliasFocusLost

    private void jtAliasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAliasFocusGained
        jtAliasCaretUpdate(null);
    }//GEN-LAST:event_jtAliasFocusGained

    private void jTDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDireccionFocusLost
        jTDireccion.setBackground(Color.white);
    }//GEN-LAST:event_jTDireccionFocusLost

    private void jTDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTDireccionFocusGained
        jTDireccionCaretUpdate(null);
    }//GEN-LAST:event_jTDireccionFocusGained
    
    /*
     * Los Permisos son:
     *  -visualizar_todo
     *  -visualizar_asignado
     *  -modificar_todo
     *  -modificar_asignado
     *  -crear_nuevo
     *  -transform
     */
    
    void CrearPermisos(){
        for(int i=1;i<=6;i+=2){
            for(int j=1;j<=6;j++){
                con.Altas("Detalle_Permiso", "", "("+i+",'"+jtAlias.getText()+"',"+j+",'Admin',curdate())");
                if(i==5){
                   con.Altas("Detalle_Permiso", "","("+ String.valueOf(i+1)+",'"+jtAlias.getText()+"',"+j+",'Admin',curdate())");
                }
            }
        }
        
        
    }
    
    public File obtenerArchivo(){
       int resultado = 0;
       JFileChooser elegir = new JFileChooser();
       
       FileView fv = new FileView() {
};
       
       elegir.setFileView(fv);
       
       elegir.setFileSelectionMode(JFileChooser.FILES_ONLY);
       resultado = elegir.showOpenDialog(this);
       if(resultado == JFileChooser.CANCEL_OPTION){
           return null;
       }
       File archivo = elegir.getSelectedFile();
       if(archivo == null){
           JOptionPane.showMessageDialog(null, "Error al cargar archivo",
                        "Error", JOptionPane.ERROR_MESSAGE);
       }
       return archivo;
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDNUsuario dialog = new JDNUsuario(new javax.swing.JFrame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTRuta;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLContraseña2;
    private javax.swing.JLabel jLIcon;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNuevo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPasswordField jPContraseña;
    private javax.swing.JPasswordField jPContraseña2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTNombre;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private javax.swing.JLabel jlAlias;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JLabel jlapellido;
    private javax.swing.JTextField jtAlias;
    private javax.swing.JTextField jtTelefono;
    private javax.swing.JTextField jtapellido;
    // End of variables declaration//GEN-END:variables
}
