/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import clases.DBConnect;
import etiproject.JDNProveedor;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ever
 */
public class jPListProveedor extends javax.swing.JPanel {
    DBConnect con;
    java.sql.ResultSet rs;
    javax.swing.table.DefaultTableModel m;
    
    /**
     * Creates new form jPListProveedor
     */
    public jPListProveedor(DBConnect con) {
        initComponents();
        this.con = con;
        preparartabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedores = new javax.swing.JTable();
        jbtAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jxtfBuscar = new org.jdesktop.swingx.JXTextField();

        jPanel1.setBackground(new java.awt.Color(195, 196, 201));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Teléfono", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProveedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 52, 1152, 585));

        jbtAgregar.setText("Agregar Proveedor");
        jbtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1061, 643, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 122, 122));
        jLabel3.setText("Buscar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 11, -1, -1));

        jxtfBuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jxtfBuscarCaretUpdate(evt);
            }
        });
        jPanel1.add(jxtfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 17, 200, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void preparartabla() {
         rs=null;
         rs=con.Listar("*", "proveedor", "");
            //String titulos[]={"Cod. Cliente", "Nombre", "Telefono", "Direccion"};
            m =(DefaultTableModel) jTableProveedores.getModel();
            jTableProveedores.setModel(m);
            String fila[] = new String[4];
            try {
            while(rs.next()){
                fila[0]=rs.getString(1);
                fila[1]=rs.getString(2);
                fila[2]=rs.getString(3);
                fila[3]=rs.getString(4);
                 m.addRow(fila);
            }

        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jbtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAgregarActionPerformed
        new JDNProveedor(null, true, con).setVisible(true);
        jxtfBuscarCaretUpdate(null);
    }//GEN-LAST:event_jbtAgregarActionPerformed

    private void jxtfBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jxtfBuscarCaretUpdate

        jTableProveedores.clearSelection();
        String titulos[]={"Código","Proveedor","Teléfono", "Dirección"};
        m = (new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Código","Proveedor","Teléfono", "Dirección"})
        {
            boolean[] canEdit = new boolean [] {false, false, false, false, false, false,false};

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }});

            jTableProveedores.setModel(m);
            m= (javax.swing.table.DefaultTableModel) jTableProveedores.getModel();
            jTableProveedores.setModel(m);

            rs=null;

            rs=con.Listar("*", "proveedor", " where (Id_proveedor like \"%"+ jxtfBuscar.getText()+"%\") OR (Nom_proveedor like \"%"+ jxtfBuscar.getText()+"%\") "
                + "OR (Tel_proveedor like \"%"+ jxtfBuscar.getText()+"%\") OR (Dir_proveedor like \"%"+ jxtfBuscar.getText()+"%\")");

            String fila[] = new String[4];

            try {
                while(rs.next()){
                    fila[0]=rs.getString("Id_proveedor");
                    fila[1]=rs.getString("Nom_proveedor");
                    fila[2]=rs.getString("Tel_proveedor");
                    fila[3]=rs.getString("Dir_proveedor");

                    m.addRow(fila);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_jxtfBuscarCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProveedores;
    private javax.swing.JButton jbtAgregar;
    private org.jdesktop.swingx.JXTextField jxtfBuscar;
    // End of variables declaration//GEN-END:variables
}
